name: Deploy to windmill.dev

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to windmill.dev
        uses: windmill-labs/windmill-gh-action-deploy@v2.0.0
        with:
          dry_run: false
          input_dir: src
          windmill_workspace: windmill-labs
          windmill_token: ${{ secrets.WINDMILL_API_TOKEN }}